# Generated by Django 5.0.6 on 2024-07-07 09:39

import django.core.validators
import django.db.models.deletion
import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.DecimalField(decimal_places=10, max_digits=20, validators=[movie.models.validate_even])),
                ('vote_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vote_average', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('tt\\d{7}', message='Proszę podać poprawny TMDB ID')])),
                ('original_title', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(3)])),
                ('overview', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('release_date', models.DateField()),
                ('statistics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movie.moviestatistics')),
            ],
        ),
    ]
