# Generated by Django 5.0.6 on 2024-07-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_moviecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.TextField(null=True),
        ),
    ]
